use crate::{Value, value::Kind};

pub(super) fn typed(value: &Value, name: &str) -> Option<&'static str> {
    match &value.0 {
        Kind::Bytes(_)
            if matches!(
                name,
                "size"
                    | "length"
                    | "bytesize"
                    | "ord"
                    | "chr"
                    | "getbyte"
                    | "byteslice"
                    | "hex"
                    | "oct"
                    | "empty?"
                    | "clear"
                    | "concat"
                    | "prepend"
                    | "insert"
                    | "replace"
                    | "start_with?"
                    | "end_with?"
                    | "include?"
                    | "count"
                    | "casecmp"
                    | "casecmp?"
                    | "between?"
                    | "match"
                    | "match?"
                    | "scan"
                    | "index"
                    | "rindex"
                    | "slice"
                    | "strip"
                    | "strip!"
                    | "squish"
                    | "squish!"
                    | "lstrip"
                    | "lstrip!"
                    | "rstrip"
                    | "rstrip!"
                    | "chomp"
                    | "chomp!"
                    | "chop"
                    | "chop!"
                    | "delete"
                    | "delete!"
                    | "delete_prefix"
                    | "delete_prefix!"
                    | "delete_suffix"
                    | "delete_suffix!"
                    | "tr"
                    | "tr!"
                    | "squeeze"
                    | "squeeze!"
                    | "upcase"
                    | "upcase!"
                    | "downcase"
                    | "downcase!"
                    | "capitalize"
                    | "capitalize!"
                    | "swapcase"
                    | "swapcase!"
                    | "reverse"
                    | "reverse!"
                    | "sub"
                    | "sub!"
                    | "gsub"
                    | "gsub!"
                    | "split"
                    | "partition"
                    | "rpartition"
                    | "chars"
                    | "lines"
                    | "bytes"
                    | "codepoints"
                    | "each_char"
                    | "each_line"
                    | "each_byte"
                    | "each_codepoint"
                    | "template"
                    | "center"
                    | "ljust"
                    | "rjust"
                    | "clamp"
                    | "inspect"
                    | "to_sym"
                    | "intern"
                    | "to_s"
                    | "string"
                    | "to_i"
                    | "to_f"
            ) =>
        {
            Some("string")
        }
        Kind::Array(_)
            if matches!(
                name,
                "size"
                    | "length"
                    | "empty?"
                    | "each"
                    | "each_with_index"
                    | "each_slice"
                    | "each_cons"
                    | "reverse_each"
                    | "cycle"
                    | "map"
                    | "map_with_index"
                    | "flat_map"
                    | "collect_concat"
                    | "filter_map"
                    | "select"
                    | "reject"
                    | "find"
                    | "find_index"
                    | "reduce"
                    | "include?"
                    | "index"
                    | "rindex"
                    | "at"
                    | "slice"
                    | "fetch"
                    | "values_at"
                    | "dig"
                    | "count"
                    | "any?"
                    | "all?"
                    | "none?"
                    | "one?"
                    | "take_while"
                    | "drop_while"
                    | "grep"
                    | "grep_v"
                    | "slice_when"
                    | "chunk_while"
                    | "push"
                    | "append"
                    | "prepend"
                    | "unshift"
                    | "pop"
                    | "shift"
                    | "delete"
                    | "insert"
                    | "clear"
                    | "delete_if"
                    | "keep_if"
                    | "uniq"
                    | "first"
                    | "last"
                    | "sum"
                    | "compact"
                    | "flatten"
                    | "fill"
                    | "chunk"
                    | "window"
                    | "join"
                    | "reverse"
                    | "to_h"
                    | "take"
                    | "drop"
                    | "zip"
                    | "transpose"
                    | "union"
                    | "difference"
                    | "sample"
                    | "shuffle"
                    | "rotate"
                    | "product"
                    | "combination"
                    | "permutation"
                    | "repeated_combination"
                    | "repeated_permutation"
                    | "sort"
                    | "sort_by"
                    | "partition"
                    | "group_by"
                    | "group_by_stable"
                    | "tally"
                    | "min"
                    | "max"
                    | "minmax"
                    | "min_by"
                    | "max_by"
                    | "inspect"
                    | "to_s"
                    | "string"
            ) =>
        {
            Some("array")
        }
        Kind::Hash(_)
            if matches!(
                name,
                "size"
                    | "length"
                    | "empty?"
                    | "key?"
                    | "has_key?"
                    | "member?"
                    | "include?"
                    | "value?"
                    | "has_value?"
                    | "keys"
                    | "values"
                    | "values_at"
                    | "fetch"
                    | "fetch_values"
                    | "dig"
                    | "each"
                    | "each_with_index"
                    | "each_key"
                    | "each_value"
                    | "to_a"
                    | "merge"
                    | "replace"
                    | "store"
                    | "delete"
                    | "clear"
                    | "delete_if"
                    | "keep_if"
                    | "slice"
                    | "except"
                    | "flatten"
                    | "select"
                    | "reject"
                    | "map"
                    | "map_with_index"
                    | "transform_keys"
                    | "deep_transform_keys"
                    | "remap_keys"
                    | "transform_values"
                    | "compact"
                    | "inspect"
            ) =>
        {
            Some("hash")
        }
        Kind::Int(_) | Kind::Big(_)
            if matches!(
                name,
                "abs"
                    | "clamp"
                    | "between?"
                    | "even?"
                    | "odd?"
                    | "times"
                    | "upto"
                    | "downto"
                    | "step"
                    | "zero?"
                    | "positive?"
                    | "negative?"
                    | "nonzero?"
                    | "next"
                    | "succ"
                    | "pred"
                    | "round"
                    | "floor"
                    | "ceil"
                    | "div"
                    | "divmod"
                    | "fdiv"
                    | "remainder"
                    | "modulo"
                    | "to_s"
                    | "string"
                    | "to_i"
                    | "to_f"
                    | "inspect"
            ) =>
        {
            Some("int")
        }
        Kind::Float(_)
            if matches!(
                name,
                "abs"
                    | "clamp"
                    | "between?"
                    | "round"
                    | "floor"
                    | "ceil"
                    | "zero?"
                    | "positive?"
                    | "negative?"
                    | "nonzero?"
                    | "nan?"
                    | "infinite?"
                    | "finite?"
                    | "div"
                    | "divmod"
                    | "fdiv"
                    | "remainder"
                    | "modulo"
                    | "to_s"
                    | "string"
                    | "to_i"
                    | "to_f"
                    | "inspect"
            ) =>
        {
            Some("float")
        }
        Kind::Bool(_) if matches!(name, "inspect" | "to_s" | "string") => Some("bool"),
        Kind::Nil if matches!(name, "inspect" | "to_s" | "string") => Some("nil"),
        Kind::Symbol(_) if matches!(name, "inspect" | "id2name" | "to_s" | "string" | "to_sym") => {
            Some("symbol")
        }
        Kind::Regex(_) if matches!(name, "match" | "match?" | "source" | "flags" | "inspect") => {
            Some("regex")
        }
        Kind::Range(_)
            if matches!(
                name,
                "cover?"
                    | "include?"
                    | "member?"
                    | "first"
                    | "last"
                    | "size"
                    | "exclude_end?"
                    | "to_a"
                    | "each"
                    | "step"
                    | "map"
                    | "select"
                    | "reject"
                    | "find"
                    | "reduce"
                    | "count"
                    | "sum"
                    | "min"
                    | "max"
                    | "to_s"
                    | "string"
                    | "inspect"
            ) =>
        {
            Some("range")
        }
        Kind::Money(_) if matches!(name, "format" | "between?") => Some("money"),
        _ => None,
    }
}

pub(super) fn universal(name: &str) -> bool {
    matches!(
        name,
        "itself"
            | "dup"
            | "clone"
            | "freeze"
            | "frozen?"
            | "nil?"
            | "eql?"
            | "equal?"
            | "send"
            | "public_send"
            | "tap"
            | "yield_self"
            | "respond_to?"
            | "is_a?"
            | "kind_of?"
            | "instance_of?"
            | "is_type?"
    )
}

pub(super) fn temporal_method(value: &Value, name: &str) -> bool {
    match value.0 {
        Kind::Money(_) => matches!(name, "to_s" | "string" | "inspect"),
        Kind::Duration(_) => matches!(
            name,
            "to_s"
                | "string"
                | "inspect"
                | "eql?"
                | "between?"
                | "after"
                | "since"
                | "from_now"
                | "ago"
                | "before"
                | "until"
        ),
        Kind::Time(_) | Kind::Zoned(_) => matches!(
            name,
            "<=>"
                | "eql?"
                | "between?"
                | "to_s"
                | "string"
                | "inspect"
                | "iso8601"
                | "xmlschema"
                | "rfc3339"
                | "httpdate"
                | "rfc2822"
                | "rfc822"
                | "format"
                | "strftime"
                | "getlocal"
                | "localtime"
                | "round"
                | "ceil"
                | "floor"
        ),
        _ => false,
    }
}
