/// The 100 largest self-contained site programs with a no-argument run entry.
// Keep their source in read-only binary pages so fixture loading is not measured.
pub const PROGRAMS: [(&str, &str); 100] = [
    (
        "rosettacode/popular/99_bottles_of_beer.vibe",
        include_str!("../../tests/site/rosettacode/popular/99_bottles_of_beer.vibe"),
    ),
    (
        "rosettacode/popular/abbreviations_automatic.vibe",
        include_str!("../../tests/site/rosettacode/popular/abbreviations_automatic.vibe"),
    ),
    (
        "rosettacode/popular/abbreviations_simple.vibe",
        include_str!("../../tests/site/rosettacode/popular/abbreviations_simple.vibe"),
    ),
    (
        "rosettacode/popular/abc_problem.vibe",
        include_str!("../../tests/site/rosettacode/popular/abc_problem.vibe"),
    ),
    (
        "rosettacode/popular/abundant_deficient_and_perfect_number_classifications.vibe",
        include_str!(
            "../../tests/site/rosettacode/popular/abundant_deficient_and_perfect_number_classifications.vibe"
        ),
    ),
    (
        "rosettacode/popular/align_columns.vibe",
        include_str!("../../tests/site/rosettacode/popular/align_columns.vibe"),
    ),
    (
        "rosettacode/popular/aliquot_sequence_classifications.vibe",
        include_str!("../../tests/site/rosettacode/popular/aliquot_sequence_classifications.vibe"),
    ),
    (
        "rosettacode/popular/angle_difference_between_two_bearings.vibe",
        include_str!(
            "../../tests/site/rosettacode/popular/angle_difference_between_two_bearings.vibe"
        ),
    ),
    (
        "rosettacode/popular/angles_geometric_normalization_and_conversion.vibe",
        include_str!(
            "../../tests/site/rosettacode/popular/angles_geometric_normalization_and_conversion.vibe"
        ),
    ),
    (
        "rosettacode/popular/bacon_cipher.vibe",
        include_str!("../../tests/site/rosettacode/popular/bacon_cipher.vibe"),
    ),
    (
        "rosettacode/popular/balanced_brackets.vibe",
        include_str!("../../tests/site/rosettacode/popular/balanced_brackets.vibe"),
    ),
    (
        "rosettacode/popular/balanced_ternary.vibe",
        include_str!("../../tests/site/rosettacode/popular/balanced_ternary.vibe"),
    ),
    (
        "rosettacode/popular/best_shuffle.vibe",
        include_str!("../../tests/site/rosettacode/popular/best_shuffle.vibe"),
    ),
    (
        "rosettacode/popular/binary_search.vibe",
        include_str!("../../tests/site/rosettacode/popular/binary_search.vibe"),
    ),
    (
        "rosettacode/popular/bitwise_operations.vibe",
        include_str!("../../tests/site/rosettacode/popular/bitwise_operations.vibe"),
    ),
    (
        "rosettacode/popular/box_the_compass.vibe",
        include_str!("../../tests/site/rosettacode/popular/box_the_compass.vibe"),
    ),
    (
        "rosettacode/popular/brazilian_numbers.vibe",
        include_str!("../../tests/site/rosettacode/popular/brazilian_numbers.vibe"),
    ),
    (
        "rosettacode/popular/caesar_cipher.vibe",
        include_str!("../../tests/site/rosettacode/popular/caesar_cipher.vibe"),
    ),
    (
        "rosettacode/popular/cartesian_product_of_two_or_more_lists.vibe",
        include_str!(
            "../../tests/site/rosettacode/popular/cartesian_product_of_two_or_more_lists.vibe"
        ),
    ),
    (
        "rosettacode/popular/day_of_the_week.vibe",
        include_str!("../../tests/site/rosettacode/popular/day_of_the_week.vibe"),
    ),
    (
        "rosettacode/popular/determine_if_a_string_is_numeric.vibe",
        include_str!("../../tests/site/rosettacode/popular/determine_if_a_string_is_numeric.vibe"),
    ),
    (
        "rosettacode/popular/discordian_date.vibe",
        include_str!("../../tests/site/rosettacode/popular/discordian_date.vibe"),
    ),
    (
        "rosettacode/popular/farey_sequence.vibe",
        include_str!("../../tests/site/rosettacode/popular/farey_sequence.vibe"),
    ),
    (
        "rosettacode/popular/find_palindromic_numbers_in_both_binary_and_ternary_bases.vibe",
        include_str!(
            "../../tests/site/rosettacode/popular/find_palindromic_numbers_in_both_binary_and_ternary_bases.vibe"
        ),
    ),
    (
        "rosettacode/popular/find_words_which_contain_the_most_consonants.vibe",
        include_str!(
            "../../tests/site/rosettacode/popular/find_words_which_contain_the_most_consonants.vibe"
        ),
    ),
    (
        "rosettacode/popular/fraction_reduction.vibe",
        include_str!("../../tests/site/rosettacode/popular/fraction_reduction.vibe"),
    ),
    (
        "rosettacode/popular/greedy_algorithm_for_egyptian_fractions.vibe",
        include_str!(
            "../../tests/site/rosettacode/popular/greedy_algorithm_for_egyptian_fractions.vibe"
        ),
    ),
    (
        "rosettacode/popular/hamming_numbers.vibe",
        include_str!("../../tests/site/rosettacode/popular/hamming_numbers.vibe"),
    ),
    (
        "rosettacode/popular/heronian_triangles.vibe",
        include_str!("../../tests/site/rosettacode/popular/heronian_triangles.vibe"),
    ),
    (
        "rosettacode/popular/humble_numbers.vibe",
        include_str!("../../tests/site/rosettacode/popular/humble_numbers.vibe"),
    ),
    (
        "rosettacode/popular/josephus_problem.vibe",
        include_str!("../../tests/site/rosettacode/popular/josephus_problem.vibe"),
    ),
    (
        "rosettacode/popular/kaprekar_numbers.vibe",
        include_str!("../../tests/site/rosettacode/popular/kaprekar_numbers.vibe"),
    ),
    (
        "rosettacode/popular/kaprekar_routine.vibe",
        include_str!("../../tests/site/rosettacode/popular/kaprekar_routine.vibe"),
    ),
    (
        "rosettacode/popular/last_letter_first_letter.vibe",
        include_str!("../../tests/site/rosettacode/popular/last_letter_first_letter.vibe"),
    ),
    (
        "rosettacode/popular/levenshtein_distance.vibe",
        include_str!("../../tests/site/rosettacode/popular/levenshtein_distance.vibe"),
    ),
    (
        "rosettacode/popular/long_multiplication.vibe",
        include_str!("../../tests/site/rosettacode/popular/long_multiplication.vibe"),
    ),
    (
        "rosettacode/popular/lychrel_numbers.vibe",
        include_str!("../../tests/site/rosettacode/popular/lychrel_numbers.vibe"),
    ),
    (
        "rosettacode/popular/magic_squares_of_odd_order.vibe",
        include_str!("../../tests/site/rosettacode/popular/magic_squares_of_odd_order.vibe"),
    ),
    (
        "rosettacode/popular/middle_three_digits.vibe",
        include_str!("../../tests/site/rosettacode/popular/middle_three_digits.vibe"),
    ),
    (
        "rosettacode/popular/morse_code.vibe",
        include_str!("../../tests/site/rosettacode/popular/morse_code.vibe"),
    ),
    (
        "rosettacode/popular/natural_sorting.vibe",
        include_str!("../../tests/site/rosettacode/popular/natural_sorting.vibe"),
    ),
    (
        "rosettacode/popular/number_names.vibe",
        include_str!("../../tests/site/rosettacode/popular/number_names.vibe"),
    ),
    (
        "rosettacode/popular/numerical_integration.vibe",
        include_str!("../../tests/site/rosettacode/popular/numerical_integration.vibe"),
    ),
    (
        "rosettacode/popular/palindrome_detection.vibe",
        include_str!("../../tests/site/rosettacode/popular/palindrome_detection.vibe"),
    ),
    (
        "rosettacode/popular/palindromic_gapful_numbers.vibe",
        include_str!("../../tests/site/rosettacode/popular/palindromic_gapful_numbers.vibe"),
    ),
    (
        "rosettacode/popular/pangram_checker.vibe",
        include_str!("../../tests/site/rosettacode/popular/pangram_checker.vibe"),
    ),
    (
        "rosettacode/popular/parse_an_ip_address.vibe",
        include_str!("../../tests/site/rosettacode/popular/parse_an_ip_address.vibe"),
    ),
    (
        "rosettacode/popular/permutations.vibe",
        include_str!("../../tests/site/rosettacode/popular/permutations.vibe"),
    ),
    (
        "rosettacode/popular/pig_latin.vibe",
        include_str!("../../tests/site/rosettacode/popular/pig_latin.vibe"),
    ),
    (
        "rosettacode/popular/playing_cards.vibe",
        include_str!("../../tests/site/rosettacode/popular/playing_cards.vibe"),
    ),
    (
        "rosettacode/popular/priority_queue.vibe",
        include_str!("../../tests/site/rosettacode/popular/priority_queue.vibe"),
    ),
    (
        "rosettacode/popular/range_extraction.vibe",
        include_str!("../../tests/site/rosettacode/popular/range_extraction.vibe"),
    ),
    (
        "rosettacode/popular/roman_numerals_decode.vibe",
        include_str!("../../tests/site/rosettacode/popular/roman_numerals_decode.vibe"),
    ),
    (
        "rosettacode/popular/rot_13.vibe",
        include_str!("../../tests/site/rosettacode/popular/rot_13.vibe"),
    ),
    (
        "rosettacode/popular/run_length_encoding.vibe",
        include_str!("../../tests/site/rosettacode/popular/run_length_encoding.vibe"),
    ),
    (
        "rosettacode/popular/sequence_of_primorial_primes.vibe",
        include_str!("../../tests/site/rosettacode/popular/sequence_of_primorial_primes.vibe"),
    ),
    (
        "rosettacode/popular/smith_numbers.vibe",
        include_str!("../../tests/site/rosettacode/popular/smith_numbers.vibe"),
    ),
    (
        "rosettacode/popular/spiral_matrix.vibe",
        include_str!("../../tests/site/rosettacode/popular/spiral_matrix.vibe"),
    ),
    (
        "rosettacode/popular/stack.vibe",
        include_str!("../../tests/site/rosettacode/popular/stack.vibe"),
    ),
    (
        "rosettacode/popular/taxicab_numbers.vibe",
        include_str!("../../tests/site/rosettacode/popular/taxicab_numbers.vibe"),
    ),
    (
        "rosettacode/popular/ternary_logic.vibe",
        include_str!("../../tests/site/rosettacode/popular/ternary_logic.vibe"),
    ),
    (
        "rosettacode/popular/top_rank_per_group.vibe",
        include_str!("../../tests/site/rosettacode/popular/top_rank_per_group.vibe"),
    ),
    (
        "rosettacode/popular/topological_sort.vibe",
        include_str!("../../tests/site/rosettacode/popular/topological_sort.vibe"),
    ),
    (
        "rosettacode/popular/tree_traversal.vibe",
        include_str!("../../tests/site/rosettacode/popular/tree_traversal.vibe"),
    ),
    (
        "rosettacode/popular/url_parser.vibe",
        include_str!("../../tests/site/rosettacode/popular/url_parser.vibe"),
    ),
    (
        "rosettacode/popular/utf_8_encode_and_decode.vibe",
        include_str!("../../tests/site/rosettacode/popular/utf_8_encode_and_decode.vibe"),
    ),
    (
        "rosettacode/popular/vigen_re_cipher.vibe",
        include_str!("../../tests/site/rosettacode/popular/vigen_re_cipher.vibe"),
    ),
    (
        "rosettacode/popular/word_frequency.vibe",
        include_str!("../../tests/site/rosettacode/popular/word_frequency.vibe"),
    ),
    (
        "rosettacode/popular/word_wrap.vibe",
        include_str!("../../tests/site/rosettacode/popular/word_wrap.vibe"),
    ),
    (
        "rosettacode/popular/zeckendorf_number_representation.vibe",
        include_str!("../../tests/site/rosettacode/popular/zeckendorf_number_representation.vibe"),
    ),
    (
        "rosettacode/popular/zig_zag_matrix.vibe",
        include_str!("../../tests/site/rosettacode/popular/zig_zag_matrix.vibe"),
    ),
    (
        "showcase/automation/maintenance_window.vibe",
        include_str!("../../tests/site/showcase/automation/maintenance_window.vibe"),
    ),
    (
        "showcase/automation/retry_backoff.vibe",
        include_str!("../../tests/site/showcase/automation/retry_backoff.vibe"),
    ),
    (
        "showcase/collections/hash_projection.vibe",
        include_str!("../../tests/site/showcase/collections/hash_projection.vibe"),
    ),
    (
        "showcase/commerce/quote_approval.vibe",
        include_str!("../../tests/site/showcase/commerce/quote_approval.vibe"),
    ),
    (
        "showcase/commerce/shipping_quote.vibe",
        include_str!("../../tests/site/showcase/commerce/shipping_quote.vibe"),
    ),
    (
        "showcase/finance/late_fee_policy.vibe",
        include_str!("../../tests/site/showcase/finance/late_fee_policy.vibe"),
    ),
    (
        "showcase/finance/payout_schedule.vibe",
        include_str!("../../tests/site/showcase/finance/payout_schedule.vibe"),
    ),
    (
        "showcase/finance/subscription_billing.vibe",
        include_str!("../../tests/site/showcase/finance/subscription_billing.vibe"),
    ),
    (
        "showcase/language/value_boundaries.vibe",
        include_str!("../../tests/site/showcase/language/value_boundaries.vibe"),
    ),
    (
        "showcase/math/chudnovsky_pi.vibe",
        include_str!("../../tests/site/showcase/math/chudnovsky_pi.vibe"),
    ),
    (
        "showcase/notifications/digest_schedule.vibe",
        include_str!("../../tests/site/showcase/notifications/digest_schedule.vibe"),
    ),
    (
        "showcase/notifications/reminder_schedule.vibe",
        include_str!("../../tests/site/showcase/notifications/reminder_schedule.vibe"),
    ),
    (
        "showcase/numbers/literals_and_rounding.vibe",
        include_str!("../../tests/site/showcase/numbers/literals_and_rounding.vibe"),
    ),
    (
        "showcase/operations/log_digest.vibe",
        include_str!("../../tests/site/showcase/operations/log_digest.vibe"),
    ),
    (
        "showcase/operations/on_call_handoff.vibe",
        include_str!("../../tests/site/showcase/operations/on_call_handoff.vibe"),
    ),
    (
        "showcase/policies/refund_decision.vibe",
        include_str!("../../tests/site/showcase/policies/refund_decision.vibe"),
    ),
    (
        "showcase/policies/trial_offer.vibe",
        include_str!("../../tests/site/showcase/policies/trial_offer.vibe"),
    ),
    (
        "showcase/security/session_expiry.vibe",
        include_str!("../../tests/site/showcase/security/session_expiry.vibe"),
    ),
    (
        "showcase/strings/text_toolkit.vibe",
        include_str!("../../tests/site/showcase/strings/text_toolkit.vibe"),
    ),
    (
        "showcase/support/escalation_policy.vibe",
        include_str!("../../tests/site/showcase/support/escalation_policy.vibe"),
    ),
    (
        "showcase/workflows/approval_chain.vibe",
        include_str!("../../tests/site/showcase/workflows/approval_chain.vibe"),
    ),
    (
        "showcase/workflows/release_readiness.vibe",
        include_str!("../../tests/site/showcase/workflows/release_readiness.vibe"),
    ),
    (
        "upstream/arrays/extras.vibe",
        include_str!("../../tests/site/upstream/arrays/extras.vibe"),
    ),
    (
        "upstream/blocks/yield_patterns.vibe",
        include_str!("../../tests/site/upstream/blocks/yield_patterns.vibe"),
    ),
    (
        "upstream/hashes/operations.vibe",
        include_str!("../../tests/site/upstream/hashes/operations.vibe"),
    ),
    (
        "upstream/hashes/transformations.vibe",
        include_str!("../../tests/site/upstream/hashes/transformations.vibe"),
    ),
    (
        "upstream/loops/iteration.vibe",
        include_str!("../../tests/site/upstream/loops/iteration.vibe"),
    ),
    (
        "upstream/strings/operations.vibe",
        include_str!("../../tests/site/upstream/strings/operations.vibe"),
    ),
    (
        "upstream/time/duration.vibe",
        include_str!("../../tests/site/upstream/time/duration.vibe"),
    ),
];
