#!/usr/bin/env python3
"""Vendor the Go reference's hover documentation and member contracts for `vibes lsp`."""
import json
import shutil
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CACHE = ROOT / '.cache/lsp-data'
CACHE.mkdir(parents=True, exist_ok=True)
OUT = ROOT / 'tools/src/lsp'
source = ROOT / 'scripts/generate-lsp-data.go'
go = ROOT / 'scripts/go'
module = ROOT / 'benchmarks/go'
assert not subprocess.check_output(['gofmt', '-l', str(source)], text=True).strip()
subprocess.run([str(go), 'vet', str(source)], cwd=module, check=True)
binary = CACHE / 'generate'
subprocess.run([str(go), 'build', '-o', str(binary), str(source)], cwd=module, check=True)
contracts = json.loads(subprocess.check_output([str(binary)]))
reference = Path(subprocess.check_output(
    [str(go), 'list', '-m', '-f', '{{.Dir}}', 'github.com/mgomes/vibescript'], cwd=module, text=True).strip())
version = subprocess.check_output(
    [str(go), 'list', '-m', '-f', '{{.Version}}', 'github.com/mgomes/vibescript'], cwd=module, text=True).strip()
assert version == 'v0.70.0', version

# The reference embeds these files for hover and completion documentation.
for name in ['builtins', 'stdlib_core_utilities', 'strings', 'arrays', 'hashes', 'time', 'durations']:
    shutil.copyfile(reference / 'docs' / f'{name}.md', OUT / 'reference' / f'{name}.md')


def text(value):
    return json.dumps(value, ensure_ascii=False)


rows = []
for contract in contracts:
    params = ', '.join(f'({text(p["Name"])}, {str(p["Optional"]).lower()})' for p in contract['Params'])
    aliases = ', '.join(text(alias) for alias in contract['Aliases'] or [])
    rows.append(f'''    Contract {{
        receiver: {text(contract["Receiver"])},
        name: {text(contract["Name"])},
        aliases: &[{aliases}],
        params: &[{params}],
        variadic: {str(contract["Variadic"]).lower()},
        takes_block: {str(contract["TakesBlock"]).lower()},
        value_member: {str(contract["ValueMember"]).lower()},
        result: {text(contract["Result"])},
    }},''')
(OUT / 'contracts.rs').write_text(f'''// Generated by scripts/generate-lsp-data.py from the Go reference {version}.

//! The reference's registered builtin member contracts, which completion
//! documentation renders as receiver-qualified signatures.

/// One member contract: its receiver kind, or `universal`, its name and
/// aliases, positional parameters with their optional flags, and call shape.
pub(crate) struct Contract {{
    pub receiver: &'static str,
    pub name: &'static str,
    pub aliases: &'static [&'static str],
    pub params: &'static [(&'static str, bool)],
    pub variadic: bool,
    pub takes_block: bool,
    pub value_member: bool,
    pub result: &'static str,
}}

pub(crate) const CONTRACTS: &[Contract] = &[
{chr(10).join(rows)}
];
''')
