#!/usr/bin/env python3
"""Generate identifier and percent-literal character classes from the Go Unicode tables.

Regenerating needs the Go 1.27.1 toolchain, whose GOROOT holds the Unicode
17.0.0 tables.
"""
import json
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
goroot = Path(subprocess.check_output(["go", "env", "GOROOT"], text=True).strip())
source = (goroot / "src/unicode/tables.go").read_text()
version = re.search(r'const Version = "([^"]+)"', source).group(1)
assert version == "17.0.0", version
tables = []
for name in ["L", "Nd", "Lu", "Ll"]:
    body = source.split(f"var _{name} = &RangeTable{{", 1)[1].split("\n}", 1)[0]
    ranges = [(int(lo, 16), int(hi, 16), int(stride))
              for lo, hi, stride in re.findall(r"\{0x([0-9a-f]+), 0x([0-9a-f]+), (\d+)\}", body)]
    assert ranges and all(a[1] < b[0] for a, b in zip(ranges, ranges[1:]))
    tables.append((name.upper(), ranges))
output = '''// Copyright 2009 The Go Authors. All rights reserved.
// Use of this source code is governed by the BSD license in licenses/Go-BSD-3-Clause.txt.
// Generated by scripts/generate-unicode.py from Go Unicode 17.0.0 tables.

pub(crate) fn letter(c: char) -> bool {
    if c.is_ascii() { c.is_ascii_alphabetic() } else { contains(L, c) }
}

pub(crate) fn digit(c: char) -> bool {
    if c.is_ascii() { c.is_ascii_digit() } else { contains(ND, c) }
}

pub(crate) fn upper(c: char) -> bool {
    if c.is_ascii() { c.is_ascii_uppercase() } else { contains(LU, c) }
}

pub(crate) fn lower(c: char) -> bool {
    if c.is_ascii() { c.is_ascii_lowercase() } else { contains(LL, c) }
}

pub(crate) fn letter_or_digit(c: char) -> bool {
    letter(c) || digit(c)
}

fn contains(ranges: &[(u32, u32, u32)], c: char) -> bool {
    let point = c as u32;
    let index = ranges.partition_point(|&(_, high, _)| high < point);
    ranges.get(index).is_some_and(|&(low, _, stride)| point >= low && (point - low) % stride == 0)
}
'''
for name, ranges in tables:
    output += f"\nconst {name}: &[(u32, u32, u32)] = &[\n"
    output += "".join(f"    (0x{lo:x}, 0x{hi:x}, {stride}),\n" for lo, hi, stride in ranges)
    output += "];\n"
path = ROOT / "src/syntax/unicode.rs"
path.write_text(output)
subprocess.run(["rustfmt", "--edition=2024", str(path)], check=True)
print(json.dumps({name: len(ranges) for name, ranges in tables}))
