#!/usr/bin/env python3
"""Generate full and simple-fold case mappings from the pinned Go reference."""
import hashlib
import json
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CACHE = ROOT / '.cache/language-string-casing'
CACHE.mkdir(exist_ok=True)
source = ROOT / 'scripts/generate-string-casing.go'
go = ROOT / 'scripts/go'
module = ROOT / 'benchmarks/go'
assert not subprocess.check_output(['gofmt', '-l', str(source)], text=True).strip()
subprocess.run([str(go), 'vet', str(source)], cwd=module, check=True)
binary = CACHE / 'generate'
subprocess.run([str(go), 'build', '-o', str(binary), str(source)], cwd=module, check=True)
raw = subprocess.check_output([str(binary)])
data = json.loads(raw)
assert (data['go'], data['text'], data['unicode'], data['cases']) == ('go1.27.1', 'v0.40.0', '17.0.0', '17.0.0'), data.keys()
(CACHE / 'reference-mappings.json').write_bytes(raw)
pool = bytearray()
indexes = {}
rows = []
for row in data['rows']:
    encoded = []
    for text in row['values']:
        if text == chr(row['rune']):
            encoded.append(0)
            continue
        value = text.encode()
        assert 0 < len(value) < 16
        if value not in indexes:
            indexes[value] = (len(pool) << 4) | len(value)
            pool.extend(value)
        encoded.append(indexes[value])
    rows.append((row['rune'], encoded, row['fold']))
output = '''// Copyright 2009, 2016 The Go Authors. All rights reserved.
// See licenses/Go-BSD-3-Clause.txt.
// Generated by scripts/generate-string-casing.py from Go 1.27.1 and x/text v0.40.0.

pub(super) const MAPPINGS: &[(u32, [u32; 5], u32)] = &[
'''
output += ''.join(f'    (0x{r:x}, {values}, 0x{fold:x}),\n' for r, values, fold in rows)
output += '];\n\npub(super) const BYTES: &[u8] = b"\\\n'
for start in range(0, len(pool), 24):
    output += '    ' + ''.join(f'\\x{byte:02x}' for byte in pool[start:start+24]) + '\\\n'
output += '";\n'
directory = ROOT / 'src/text/case'
directory.mkdir(parents=True, exist_ok=True)
path = directory / 'data.rs'
path.write_text(output)
subprocess.run(['rustfmt', '--edition=2024', str(path)], check=True)
manifest = {key: data[key] for key in ['go', 'text', 'unicode', 'cases']}
manifest.update(rows=len(rows), mapping_bytes=len(pool), reference_sha256=hashlib.sha256(raw).hexdigest())
(directory / 'manifest.json').write_text(json.dumps(manifest, indent=2)+'\n')
print(json.dumps(manifest), flush=True)
