#!/usr/bin/env python3
"""Generate RE2 Unicode categories, scripts, aliases and simple-fold orbits."""
import argparse
import hashlib
from pathlib import Path
import re
import subprocess

ROOT = Path(__file__).resolve().parent.parent


def generate():
    goroot = Path(subprocess.check_output([str(ROOT / 'scripts/go'), 'env', 'GOROOT'], text=True).strip())
    source = (goroot / 'src/unicode/tables.go').read_bytes()
    text = source.decode()
    assert 'const Version = "17.0.0"' in text
    names = []
    for table in ['Categories', 'Scripts']:
        body = re.search(r'var ' + table + r' = map\[string\]\*RangeTable\{(.*?)\n\}', text, re.S).group(1)
        names += re.findall(r'"([A-Za-z_]+)":', body)
    names = sorted(names)
    ranges = []
    entries = []
    for name in names:
        body = re.search(r'var _' + name + r' = &RangeTable\{(.*?)\n\}', text, re.S).group(1)
        rows = [tuple(int(n, 0) for n in row) for row in re.findall(r'\{(0x[0-9a-fA-F]+), (0x[0-9a-fA-F]+), (\d+)\}', body)]
        assert rows and rows == sorted(rows)
        assert all(lo <= hi and stride > 0 for lo, hi, stride in rows)
        entries.append((len(ranges), len(rows)))
        ranges += rows
    canonical = lambda name: re.sub(r'[_ -]', '', name).lower()
    aliases = {canonical(name): names.index(name) for name in names}
    body = re.search(r'var CategoryAliases = map\[string\]string\{(.*?)\n\}', text, re.S).group(1)
    for name, actual in re.findall(r'"([A-Za-z_]+)":\s*"([A-Za-z]+)"', body):
        assert actual in names
        aliases[canonical(name)] = names.index(actual)
    body = re.search(r'var caseOrbit = \[\]foldPair\{(.*?)\n\}', text, re.S).group(1)
    orbit = [tuple(int(n, 16) for n in row) for row in re.findall(r'\{(0x[0-9A-Fa-f]+), (0x[0-9A-Fa-f]+)\}', body)]
    assert orbit == sorted(orbit)
    out = '// Generated by scripts/generate-regex-unicode.py; see licenses/regex-NOTICE.txt.\n'
    out += '// Go Unicode 17.0.0 table SHA-256: ' + hashlib.sha256(source).hexdigest() + '\n\n'
    out += 'pub(super) const NAMES: &[(&str, usize)] = &[\n'
    out += ''.join(f'    ("{name}", {index}),\n' for name, index in sorted(aliases.items())) + '];\n\n'
    out += 'pub(super) const GROUPS: &[(usize, usize)] = &[\n'
    out += ''.join(f'    ({start}, {size}),\n' for start, size in entries) + '];\n\n'
    out += 'pub(super) const RANGES: &[(u32, u32, u32)] = &[\n'
    out += ''.join(f'    (0x{lo:x}, 0x{hi:x}, {stride}),\n' for lo, hi, stride in ranges) + '];\n\n'
    out += 'pub(super) const ORBIT: &[(u32, u32)] = &[\n'
    out += ''.join(f'    (0x{lo:x}, 0x{hi:x}),\n' for lo, hi in orbit) + '];\n'
    return subprocess.run(['rustfmt', '--emit', 'stdout', '--edition', '2024'], input=out, text=True, capture_output=True, check=True).stdout


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    data = generate()
    path = ROOT / 'src/regex/unicode/data.rs'
    if args.check:
        assert path.read_text() == data, 'regex Unicode data differs from the reference'
    else:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(data)
    print('Verified regex Unicode data' if args.check else 'Generated regex Unicode data')


if __name__ == '__main__':
    main()
