#!/usr/bin/env python3
"""Generate simple case mappings from the pinned Go Unicode tables.

Regenerating needs the Go 1.27.1 toolchain, whose GOROOT holds the Unicode
17.0.0 tables.
"""
import json
import re
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
goroot = Path(subprocess.check_output(['go', 'env', 'GOROOT'], text=True).strip())
source = (goroot / 'src/unicode/tables.go').read_text()
version = re.search(r'const Version = "([^"]+)"', source).group(1)
assert version == '17.0.0', version
body = source.split('var _CaseRanges = []CaseRange{', 1)[1].split('\n}', 1)[0]
ranges = []
for lo, hi, upper, lower, title in re.findall(r'\{0x([0-9A-F]+), 0x([0-9A-F]+), d\{([^,]+), ([^,]+), ([^}]+)\}\}', body):
    delta = lambda text: 0x110000 if text == 'UpperLower' else int(text)
    ranges.append((int(lo, 16), int(hi, 16), delta(upper), delta(lower)))
assert len(ranges) > 300
assert all(a[1] < b[0] for a, b in zip(ranges, ranges[1:]))
output = '''// Copyright 2009 The Go Authors. All rights reserved.
// Use of this source code is governed by the BSD license in licenses/Go-BSD-3-Clause.txt.
// Generated by scripts/generate-casing.py from Go Unicode 17.0.0 tables.

pub(crate) fn map(c: char, upper: bool) -> char {
    let point = c as u32;
    let index = RANGES.partition_point(|&(_, high, _, _)| high < point);
    let Some(&(low, _, up, down)) = RANGES.get(index).filter(|&&(low, _, _, _)| point >= low) else {
        return c;
    };
    let delta = if upper { up } else { down };
    let mapped = if delta == 0x110000 {
        low + ((point - low) & !1) + u32::from(!upper)
    } else {
        (point as i32 + delta) as u32
    };
    char::from_u32(mapped).unwrap()
}

const RANGES: &[(u32, u32, i32, i32)] = &[
'''
output += ''.join(f'    (0x{lo:x}, 0x{hi:x}, {up}, {down}),\n' for lo, hi, up, down in ranges)
output += '];\n'
path = ROOT / 'src/casing.rs'
path.write_text(output)
subprocess.run(['rustfmt', '--edition=2024', str(path)], check=True)
print(json.dumps({'version': version, 'ranges': len(ranges)}))
