#!/usr/bin/env python3
"""Copy the pinned timezone database and generate Windows abbreviation mappings.

Regenerating needs the Go 1.27.1 toolchain, whose GOROOT holds the database
and the Windows mappings.
"""
import hashlib
import json
import re
import subprocess
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
GOROOT = Path(subprocess.check_output(['go', 'env', 'GOROOT'], text=True).strip())
archive = GOROOT / 'lib/time/zoneinfo.zip'
expected = 'b2d18a7c8fa8142097a48c99609fb3c92db5ee98bc740294e57eab8ae9f94779'
raw = archive.read_bytes()
assert hashlib.sha256(raw).hexdigest() == expected, 'timezone database differs from the pinned Go 1.27.1 database'
with zipfile.ZipFile(archive) as z:
    assert len(z.infolist()) == 598
    assert all(i.compress_type == zipfile.ZIP_STORED and z.read(i.filename).startswith(b'TZif') for i in z.infolist())
path = ROOT / 'src/time/zone/data'
path.mkdir(exist_ok=True)
(path / 'zoneinfo.zip').write_bytes(raw)
source = (GOROOT / 'src/time/zoneinfo_abbrs_windows.go').read_text()
windows_hash = 'fdabcbf35b6e9613c7e12bc44a10701cabf08c1760aef7be07f58609dfb89ead'
assert hashlib.sha256(source.encode()).hexdigest() == windows_hash, 'Windows timezone mappings differ from the pinned source'
entries = sorted(re.findall(r'"([^"]+)":\s*\{"([^"]*)", "([^"]*)"\}', source))
assert len(entries) > 130
output = '''// Copyright 2013 The Go Authors. All rights reserved.
// See licenses/Go-BSD-3-Clause.txt.
// Generated by scripts/generate-timezones.py from Go 1.27.1.

pub(super) const ABBREVIATIONS: &[(&str, &str, &str)] = &[
'''
output += ''.join(f'    ({json.dumps(name)}, {json.dumps(std)}, {json.dumps(dst)}),\n' for name, std, dst in entries)
output += '];\n'
(path / 'windows.rs').write_text(output)
subprocess.run(['rustfmt', '--edition=2024', str(path / 'windows.rs')], check=True)
(path / 'manifest.json').write_text(json.dumps({'go': '1.27.1', 'tzdata': '2026c', 'sha256': expected, 'bytes': len(raw), 'zones': 598, 'windows_abbreviations': len(entries), 'windows_source_sha256': windows_hash}, indent=2)+'\n')
print((path / 'manifest.json').read_text())
