#!/usr/bin/env python3
"""Generate Go's Unicode printability table for quoted shape field names.

Regenerating or checking needs the Go 1.27.1 toolchain, whose GOROOT holds
strconv's tables.
"""
import argparse
import hashlib
from pathlib import Path
import re
import subprocess

ROOT = Path(__file__).resolve().parent.parent

def generate():
    goroot = Path(subprocess.check_output(['go', 'env', 'GOROOT'], text=True).strip())
    source = (goroot / 'src/strconv/isprint.go').read_bytes()
    tables = {}
    for name in ['isPrint16', 'isNotPrint16', 'isPrint32', 'isNotPrint32']:
        body = re.search(r'var ' + name + r' = \[\]uint\d+\{[^\n]*\n(.*?)\n\}', source.decode(), re.S).group(1)
        tables[name] = [int(v, 16) for v in re.findall(r'0x[0-9a-fA-F]+', body)]
    pairs = []
    for name in ['isPrint16', 'isPrint32']:
        values = tables[name]; assert len(values) % 2 == 0
        pairs += list(zip(values[::2], values[1::2]))
    exceptions = tables['isNotPrint16'] + [0x10000 + n for n in tables['isNotPrint32']]
    assert pairs == sorted(pairs) and exceptions == sorted(exceptions)
    out = '// Generated by scripts/generate-printable.py; see licenses/printable-NOTICE.txt.\n'
    out += '// Reference SHA-256: ' + hashlib.sha256(source).hexdigest() + '\n\n'
    out += '''pub(crate) fn is_print(rune: char) -> bool {
    let rune = rune as u32;
    let index = RANGES.partition_point(|&(start, _)| start <= rune);
    index > 0 && rune <= RANGES[index - 1].1 && EXCEPTIONS.binary_search(&rune).is_err()
}

const RANGES: &[(u32, u32)] = &[
'''
    out += ''.join(f'    (0x{start:x}, 0x{end:x}),\n' for start, end in pairs)
    out += '];\n\nconst EXCEPTIONS: &[u32] = &[\n'
    for i in range(0, len(exceptions), 8):
        out += '    ' + ', '.join(f'0x{n:x}' for n in exceptions[i:i+8]) + ',\n'
    out += '];\n'
    return subprocess.run(['rustfmt', '--emit', 'stdout', '--edition', '2024'], input=out, text=True, capture_output=True, check=True).stdout

def main():
    parser = argparse.ArgumentParser(); parser.add_argument('--check', action='store_true'); args = parser.parse_args()
    path = ROOT / 'src/printable.rs'; data = generate()
    if args.check:
        assert path.read_text() == data, 'printability table differs from its reference'
    else:
        path.write_text(data)
    print('Go printability table verified' if args.check else 'Generated Go printability table')

if __name__ == '__main__':
    main()
